const myExpcetion = require("./exception.js")

module.exports = async function exception(msg) {
    
    // try {
        await myExceptioin("ex");
    // }
    // catch (e) {
        // console.log("예외를 먹었습니다.");
    // }

}